site_name: Road Map
site_description: A site to map couriosities
repo_url: https://github.com/agconti/roadmap
docs_dir: site
site_dir: _site
copyright: Copyright &copy; 2015, <a href="https://github.com/agconti">agconti</a>.
pages:
  - Home: 'index.md'
  - Skills:
    - index: 'skills/index.md'
    - nosql: 'skills/nosql.md'
    - machine-learning: 'skills/machine-learning.md'
    - static-sites: 'skills/static-sites.md'
  - Proposals: 'proposals/index.md'
