site_name: Road Map
site_description: A site to map couriosities
repo_url: https://github.com/agconti/roadmap
docs_dir: site
site_dir: _site
copyright: Copyright &copy; 2015, <a href="https://github.com/agconti">agconti</a>.
pages:
  - Home: 'index.md'
  - Skills:
    - Home: 'skills/index.md'
    - "ES6 / ES7": 'skills/es6-es7.md'
    - "Angular 2": 'skills/angular-2.md'
    - NoSQL: 'skills/nosql.md'
    - "Machine Learning": 'skills/machine-learning.md'
    - "Static Sites": 'skills/static-sites.md'
  - Proposals:
    - Home: 'proposals/index.md'
    - "Building client side apps with Travis": 'proposals/building-client-side-apps-with-travis.md'
    - Rogojs: "proposals/rogojs.md"
    - "The State of static site testing": "proposals/the-state-of-static-site-testing.md"
    - "App Metrics Page": 'proposals/app-metrics-page.md'
